name: test

on:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y firefox
          sudo apt install -y firefox-geckodriver
          pip install --user --upgrade pip
          pip install --user pytest
          if [ -f requirements.txt ]; then pip install --user -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest -s